import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <UserProvider>
      <html lang="en">
        <body className={`${inter.className} bg-white dark:bg-zinc-900 text-black dark:text-white flex flex-col h-screen`}>
          <header className='container'>
            <meta charSet='utf-8' />
          </header>
          <main className='container mx-auto'>
            {children}
          </main>
          <footer className='container mt-auto'>
            <p className='text-center text-sm py-3'>
              Powered by Tom Dickman
            </p>
          </footer>
        </body>
      </html>
    </UserProvider>
  )
}
